baseURL = 'https://shirin9345.github.io/'
languageCode = 'zh-cn'
title = 'Shirin9345 Blog'
theme = 'hugo-theme-stack'

[params]
    description = "我的个人博客"
    
    [params.sidebar]
        emoji = "🍥"
        subtitle = "探索技术与生活"
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.png"

    [params.comments]
        enabled = true
        provider = "utterances"
        [params.comments.utterances]
            repo = "ShiRin9345/ShiRin9345.github.io"
            issueTerm = "pathname"
            label = "Comment"
            theme = "github-light"

    # 配置侧边栏挂件
    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'