baseURL = 'https://shirin9345.github.io/'
languageCode = 'zh-cn'
DefaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
title = 'Shirin9345 Blog'
theme = 'hugo-theme-stack'

[pagination]
  pagerSize = 8

[params]
    description = "我的个人博客"
    [params.dateFormat]
        published = "2006-01-02"
        lastUpdated = "2006-01-02 15:04"
    [params.article]
        wordCount = true
        [params.article.license]
            enabled = true
            default = 'LICENSED UNDER CC BY-NC-SA 4.0 · 转载请在留言板告知'
    [params.sidebar]
        emoji = "🍥"
        subtitle = "探索技术与生活"
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.png"

    [params.comments]
        enabled = true
        provider = "utterances"
        [params.comments.utterances]
            repo = "ShiRin9345/ShiRin9345.github.io"
            issueTerm = "pathname"
            label = "Comment"
            theme = "github-light"

    # 配置侧边栏挂件
    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
# 社交链接（侧边栏图标）
[[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ShiRin9345"
    weight = 1
    params = { icon = "brand-github" }

[[menu.social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 2
    params = { icon = "rss" }

[[menu.social]]
    identifier = "mail"
    name = "E-mail"
    url = "mailto:shirin9345@163.com"
    weight = 3
    params = { icon = "mail" }

[[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    params = { icon = "home" }
