baseURL = 'https://shirin9345.github.io/'
languageCode = 'zh-cn'
title = 'Shirin9345 Blog'
theme = 'hugo-theme-stack'

[params]
    # 基础信息配置
    description = "我的个人博客"
    
    [params.sidebar]
        emoji = "🍥"
        subtitle = "探索技术与生活"
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.jpeg"

    [params.comments]
        enabled = true
        provider = "utterances"

        [params.comments.utterances]
            repo = "ShiRin9345/ShiRin9345.github.io"
            issueTerm = "pathname"
            label = "Comment"
            theme = "github-light"

[caches]
  [caches.images]
    dir = ':cacheDir/images'